import Head from "next/head";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import Image from "next/image";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Rick & Morty</title>
        <meta name="description" content="Generated by Rick & Morty Co." />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="logo">
        <Image src="/images/icon.png" width="350" height="350" />
      </div>
      <h1 className={styles.title}>Welcome to Rick and Morty Info page.</h1>
      <p className={styles.text}>
        You Can Navigate to Episodes And Characters Page from here.
      </p>
      <Link href="/episodes">
        <a>Episodes</a>
      </Link>
      <br />
      <Link href="/characters">
        <a>Characters</a>
      </Link>

      <div className="card" style={{ width: "18rem" }}>
        <div className="card-body">
          <h5 className="card-title">Episode</h5>
          <a href="#" className="card-link">
            Card link
          </a>
        </div>
      </div>
    </div>
  );
}
